version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    groups:
      android-gradle-toolchain:
        patterns:
          - com.android.application
          - gradle-wrapper

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
